### PR TITLE
tools: Add prepare-commit-msg hook

### PR DESCRIPTION
**Pull request by joebonrichie**
This will try to prefill the commit msg based on the diff, e.g. pkg: Update to n.n.n or pkg: Add at n.n.n

It'll also give some guidance for writing the commit message.

Use `just init` to setup.

### CODE REVIEW

**Comment by joebonrichie** [comment]
Will need some handling here whether pyyaml is installed or not, otherwise feel free to try out

**Comment by ermo** [comment]
> Will need some handling here whether pyyaml is installed or not, otherwise feel free to try out

Currently, pyyaml is not available in the repos, so the smart move is probably to package it up as part of this PR...?

**Comment by joebonrichie** [comment]
uses json from stdlib to parse the manifest.jsonc file instead to avoid dependencies. JSONDecoder is overridden to handle the comment in the .jsonc file.

**Comment by joebonrichie** [comment]
Automatic "Add at ${version}" hooked up

**Review by ermo — APPROVED** [review]
I like this.

**Pull request merged**
