### PR TITLE
tools: Add new function to bash helpers and new helpers for other shells 

### PR DESCRIPTION
**Pull request by malfisya**
**Summary**

- Add `gotoserpentrepo` function to bash helper script
- Add basic script to navigate the monorepo in fish and zsh

### CODE REVIEW

**Comment by malfisya** [comment]
I only tested the bash script and the experience wasn't not starightforward. In Solus, I can just symlink the script to `~/.bashrc.d/` and it will just work. In Serpent, I have to copy the `/usr/share/defaults/etc/profile` to `/etc/bashrc` and added  this line (mimiicking what Solus does in its equivalent file):

```
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
	if [ -f "$rc" ]; then
	    . "$rc"
	fi
    done
    unset rc
fi
```
I have not tested  the zsh and fish script. Cheers!

**Comment by ermo** [comment]
we keep this sort of stuff in the [`tools/` dir](https://github.com/serpent-os/recipes/tree/main/tools) -- I think Joey already added a few helpers for bash?

Feel free to update and merge as appropriate.

Thanks!

**Comment by ermo** [comment]
> I only tested the bash script and the experience wasn't not starightforward. In Solus, I can just symlink the script to `~/.bashrc.d/` and it will just work. In Serpent, I have to copy the `/usr/share/defaults/etc/profile` to `/etc/bashrc` and added this line (mimiicking what Solus does in its equivalent file):
> 
> ```
> if [ -d ~/.bashrc.d ]; then
>     for rc in ~/.bashrc.d/*; do
> 	if [ -f "$rc" ]; then
> 	    . "$rc"
> 	fi
>     done
>     unset rc
> fi
> ```
> 
> I have not tested the zsh and fish script. Cheers!

The real solution is to do this:
1. Add a `~/.bash_profile` that `~/.bashrc`
2. Add a `~/.bashrc` that first sources `/usr/share/defaults/etc/profile` and then adds the .bashrc.d stanza you have above.

We need to make this the default in the (the equivalent to) /etc/skel for Serpent at some point soon.

**Comment by malfisya** [comment]
> The better solution might be this:
> 
>     1. Add a `~/.bash_profile` that does a `source ~/.bashrc`
> 
>     2. Add a `~/.bashrc` that first sources `/usr/share/defaults/etc/profile` and then adds the .bashrc.d stanza you have above.

This works. Thank you.

I moved the scripts to be under `tools/` directory. I don't want to disrupt the current workflow, so the function to navigate between package dir is still `chpkg` instead of `gotopkg` like in Solus. I still have not tested the zsh and fish script yet, as I am not feeling well these few days. Theoretically, they should work as they did in Solus. Cheers!

**Comment by malfisya** [comment]
> Feel free to update and merge as appropriate.

Well, I updated it but merging? Come one ermo this is Serpent 😆

**Review by ermo — CHANGES_REQUESTED** [review]
Please rename the bash script from `.sh` to `.bash`.

Looks good otherwise.

**Review by ermo — APPROVED** [review]
This looks like a decent start.

Thanks!

**Pull request merged**
